name: CI/CD Pipeline

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: npm install and npm CI commands
        run: |
          npm i
          npm run test:core:ci
          npm run build:core:ci

      - name: Check for build
        run: |
            ls -l
  
      - name: Publish to npm
        run: npm publish dist/outsiderninjadevs/core --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

