name: CI/CD Angular Quality Gate

on:
  push:
    branches: [csv, master]

  pull_request:
    branches: [csv, master]

jobs:
  build:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        node: [17.x, 18.x]
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}

      - name: npm install
        run: npm i

      - name: Run Tests
        run: npm run test:core:ci

      - name: Run Lint
        run: |
          npm run lint:core:ci
